-- AlterTable
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "archived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "archivedGradingKeys" JSONB NOT NULL DEFAULT '[]';
